{
  # Generated by 'detect-hardware desktop'. Safe to hand-edit afterwards -
  # re-running detect-hardware won't overwrite this without --force.
  hardwareProfile.gpu = {
    mode = "discrete";
    integratedVendor = null;
    discreteVendor = "amd";
    displayVendor = "amd";
    computeVendor = "amd";
    computeBackend = "rocm";
    offload = null;
  };
}
