{ ... }:

# Placeholder for host-specific monitor wiring.
#
# ~/.config/hypr/monitors.conf is generated by nwg-displays and sourced from
# hyprland.conf directly (see the home/ dotfiles repo), so nothing is needed
# at the NixOS level yet. This module intentionally does nothing.
{
}
