{ ... }:

# Placeholder for host-specific monitor wiring.
#
# ~/.config/hypr/monitors.conf is generated by nwg-displays and sourced from
# hyprland.conf directly. It's seeded (not symlinked) by home-manager so
# nwg-displays can keep rewriting it after the initial rebuild - see the
# home.activation.seedMonitorsConf block in each host's home.nix. This
# module intentionally does nothing at the NixOS level.
{
}
