{ ... }:

# Placeholder for host-specific monitor wiring.
#
# ~/.config/hypr/monitors.conf is currently generated by nwg-displays but is
# NOT sourced from hyprland.conf on the desktop host (pre-existing gap,
# preserved as-is during migration; see repo history/README for details).
# This module intentionally does nothing yet.
{
}
