# HyprEmoji Configuration
# https://github.com/Musagy/hypremoji

# Keybind to open hypremoji
bind = SUPER, period, exec, hypremoji

# Window rules for HyprEmoji
windowrule = float, title:^(HyprEmoji)$
windowrule = move cursor_x-(window_w*0.5) cursor_y-(window_h*0.05), title:^(HyprEmoji)$
