wallpaper {
    monitor = DP-1
    path = /home/nanixtus/.config/wallpapers/matrix.png
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-1
    path = /home/nanixtus/.config/wallpapers/matrix.png
    fit_mode = cover
}

wallpaper {
    monitor = eDP-1
    path = /home/nanixtus/.config/wallpapers/matrix.png
    fit_mode = cover
}

splash = false
ipc = on

