#!/usr/bin/env bash
set -euo pipefail

# Runs detect-gpu once and writes its result as a plain declarative
# hosts/<host>/hardware-gpu.nix (hardwareProfile.gpu.* - see
# modules/hardware/hardware-profile.nix for the option definitions). Nix
# itself never runs this - it's an explicit, imperative, run-once setup
# step; everything after that is just data read by hosts/<host>/default.nix.
#
# Usage: detect-hardware <desktop|laptop> [--force]

# Same fixed clone location assumed elsewhere in this repo (see
# modules/desktop/devshell-picker.nix) - not derived from $PWD.
repo="/home/nanixtus/nixos-config"

if [ "$#" -lt 1 ]; then
  echo "usage: detect-hardware <desktop|laptop> [--force]" >&2
  exit 1
fi

host="$1"
force="${2:-}"
target="$repo/hosts/$host/hardware-gpu.nix"

if [ ! -d "$repo/hosts/$host" ]; then
  echo "error: no such host: $repo/hosts/$host" >&2
  exit 1
fi

if [ -e "$target" ] && [ "$force" != "--force" ]; then
  echo "$target already exists - leaving it as-is (pass --force to regenerate)"
  exit 0
fi

status=0
json=$(detect-gpu) || status=$?

if [ "$status" -ne 0 ]; then
  echo "detect-gpu could not classify the GPU topology unambiguously:" >&2
  echo "$json" >&2
  echo "Write $target by hand instead (see modules/hardware/hardware-profile.nix)." >&2
  exit 1
fi

mode=$(jq -r '.mode' <<<"$json")
integratedVendor=$(jq -r '.integratedVendor' <<<"$json")
discreteVendor=$(jq -r '.discreteVendor' <<<"$json")
displayVendor=$(jq -r '.displayVendor' <<<"$json")
computeVendor=$(jq -r '.computeVendor' <<<"$json")
computeBackend=$(jq -r '.computeBackend' <<<"$json")
offload=$(jq -r '.offload' <<<"$json")

nix_lit() {
  if [ "$1" = "null" ]; then
    echo null
  else
    printf '"%s"' "$1"
  fi
}

cat > "$target" <<EOF
{
  # Generated by 'detect-hardware $host'. Safe to hand-edit afterwards -
  # re-running detect-hardware won't overwrite this without --force.
  hardwareProfile.gpu = {
    mode = $(nix_lit "$mode");
    integratedVendor = $(nix_lit "$integratedVendor");
    discreteVendor = $(nix_lit "$discreteVendor");
    displayVendor = $(nix_lit "$displayVendor");
    computeVendor = $(nix_lit "$computeVendor");
    computeBackend = $(nix_lit "$computeBackend");
    offload = $(nix_lit "$offload");
  };
}
EOF

echo "wrote $target: mode=$mode displayVendor=$displayVendor computeVendor=$computeVendor computeBackend=$computeBackend"
